# Start up an interactive Python session and try typing in each of the 
# following commands. Write down the results you see.
# a) print("Hello, world!")
# b) print("Hello", "world!")
# c) print(3)
# d) print(3.0)
# e) print(2 + 3)
# f) print(2.0 + 3.0)
# g) print("2" + "3")
# h) print("2 + 3 =", 2 + 3)
# i) print(2 * 3)
# j) print(2 *x 3)
# k) print(7 / 3)
# 1) print(7 // 3)

print("Hello, world!")
print("Hello", "world!")
print(3)
print(3.0)
print(2 + 3)
print(2.0 + 3.0)
print("2" + "3")
print("2 + 3 = ", 2 + 3)
print(2 * 3)
print(2 ** 3)
print(7 / 3)
print(7 // 3)