# Review Questions

# True/False
# 1.    A Python string literal is always enclosed in double quotes.    False
# 2.    The last character of a string s is at position len(s)-1.       True
# 3.    A string always contains a single line of text.                 False
# 4.    In Python "4" + "5" is "45".                                    True
# 5.    In Python "2" * 2 is 4.                                         False
# 6.    A string variable cannot be used as an accumulator.             False
# 7.    ASCII is a standard for representing characters using numeric
#       codes.                                                          True
# 8.    The split method breaks a string into a list of substrings,
#       and join does the opposite.                                     True
# 9.    A substitution cipher is a good way to keep sensitive
#       information secure.                                             False
# 10.   Expressions embedded inside f-strings are denoted with square
#       brackets ([]).                                                  False

# Multiple Choice
# 1.    Accessing a single character out of a string is called:
#     X a) slicing
#       b) concatenation
#       c) assignment
#       d) indexing
# 2.    Which of the following is the same as s[0:-1]?
#       a) s[-1]
#     X b) s[:]
#       c) s[:len(s)-1]
#       d) s[0:len(s)]
# 3.    What function gives the Unicode value of a character?
#     X a) ord
#       b) ascii
#       c) chr
#       d) eval
# 4.    Which of the following can not be used to convert a string of
#       digits into a number?
#       a) int
#       b) float
#     X c) str
#       d) eval
# 5.    A successor to ASCII that includes characters from (nearly) all
#       written languages is
#       a) TELLI
#       b) ASCII++
#     X c) Unicode
#       d) ISO
# 6.    Which string method converts all the characters of a string to upper 
#       case?
#       a) capitalize
#       b) capwords
#       c) uppercase
#     X d) upper
# 7.    Which of the following is not a string method in Python?
#       a) strip
#       b) find
#     X c) cut
#       d) lower
# 8.    What does "a fat cat".split() produce?
#       a) [a, fat, cat]
#     X b) ["a", "fat", "cat"]
#       c) [1, 3, 3]
#       d) ["a fat", " cat"]
# 9.    The expression “slots” in an f-string are denoted with
#       a) %
#       b) $
#       c) []
#     X d) {}
# 10.   What does the expression f"{3 + 4} == {4 + 3}" produce?
#       a) True
#       b) False
#       c) "3 + 4 == 4 + 3"
#     X d) "7 == 7"

# Discussion
# 1.    Given the initial statements:
#           s1 = "spam"
#           s2 = "ni!"
#       Show the result of evaluating each of the following string expressions.
#       a) "The Knights who say, " + s2             "The Knights who say, ni!"
#       b) 3 * s1 + 2 * s2                          "spamspamspamni!ni!"
#       c) s1[1]                                    "p"
#       d) s1[1:3]                                  "pa"
#       e) s1[2] + s2[:2]                           "ani"
#       f) s1 + s2[-1]                              "spam!"
#       g) s1.upper()                               "SPAM"
#       h) s2.upper().ljust(4) * 3                  "NI! NI! NI! "
# 2.    Given the same initial statements as in the previous problem, show a
#       Python expression that could construct each of the following results
#       by performing string operations on s1 and s2.
#       a) "NI"                                     s2.upper()[:-1]
#       b) "ni!spamni!"                             s2 + s1 + s2
#       c) "Spam Ni!  Spam Ni!  Spam Ni!"
#                           ((s1 + " " + s2).title().ljust(10) * 3).rstrip()
#       d) "spam"                                   s1
#       e) ["sp", "m"]                              s1.split('a')
#       f) "spm"                                    s1[:2] + s1[3:]
# 3.    Show the output that would be generated by each of the following
#       program fragments:
#       a)  for ch in "aardvark":
#               print(ch)
#           a
#           a
#           r
#           d
#           v
#           a
#           r
#           k
#       b)  for w in "Now is the winter of our discontent...".split():
#               print (w)
#           Now
#           is
#           the
#           winter
#           of
#           our
#           discontent...
#       c)  for w in "Mississippi".split("i"):
#               print(w, end=" ")
#           M ss ss pp
#       d)  print("I".join("Mississippi”.split("i")))
#           MIssIssIppI
#       e)  msg=""
#           for s in "secret".split("e"):
#               msg = msg + s
#           print (msg)
#           scrt
#       f)  msg=""
#           for ch in "secret":
#               msg = msg + chr(ord(ch)+1)
#           print (msg)
#           tfdsfu
# 4.    Given the initial statements
#           s1 = "spam"
#           s2 = "eggs"
#           num1 = 10
#           num2 = 3.14159
#       Show the string that would be produced by the following f-string
#       expressions.
#       a) f"That is {num1} {s1} and {num1//2} {s2}"
#           That is 10 spam and 5 eggs
#       b) f"That is {num1:5} {s1} and {num2:5.2} {s2}"
#           That is    10 spam and    3.1 eggs
#       c) f"{num1:0.2f} {num2:0.2f}"
#           10.00 3.14
#       d) f"{num1:7.5f}{num2:7.5f}"
#           10.000003.14159
#       e) f"Time left {num1:02}:{num2:05.0f}"
#           Time left 10:00003
# 5.    Explain why public key encryption is more useful for securing
#       communications on the Internet than private (shared) key encryption.
#       Public key encryption does not require sharing a single private key
#       with the whole Internet which would then make it incecure.