# Write a program that draws five dice on the screen depicting a straight (1,
# 2,3,4,5 or 2,3,4,5,6).

import graphics

def main():
    win = graphics.GraphWin()
    win.setCoords(0, 0, 210, 210)

    hidden_dice = graphics.Rectangle(graphics.Point(0, 0),
                                    graphics.Point(30, 30))
    hidden_dot = graphics.Circle(graphics.Point(0, 0), 3)
    hidden_dot.setFill("black")

    one = hidden_dice.clone()
    one.move(30, 210 * 3/5)
    one.draw(win)
    center = one.getCenter()
    dot = hidden_dot.clone()
    dot.move(center.getX(), center.getY())
    dot.draw(win)

    two = one.clone()
    two.move(60, 0)
    two.draw(win)
    center = two.getCenter()
    dot = hidden_dot.clone()
    dot.move(center.getX() - 5, center.getY() + 5)
    dot.draw(win)
    dot = hidden_dot.clone()
    dot.move(center.getX() + 5, center.getY() - 5)
    dot.draw(win)

    three = two.clone()
    three.move(60, 0)
    three.draw(win)
    center = three.getCenter()
    dot = hidden_dot.clone()
    dot.move(center.getX(), center.getY())
    dot.draw(win)
    dot = hidden_dot.clone()
    dot.move(center.getX() - 7, center.getY() + 7)
    dot.draw(win)
    dot = hidden_dot.clone()
    dot.move(center.getX() + 7, center.getY() - 7)
    dot.draw(win)

    four = hidden_dice.clone()
    four.move(210 * 2/7, 210 * 2/5)
    four.draw(win)
    center = four.getCenter()
    dot = hidden_dot.clone()
    dot.move(center.getX() - 5, center.getY() + 5)
    dot.draw(win)
    dot = hidden_dot.clone()
    dot.move(center.getX() - 5, center.getY() - 5)
    dot.draw(win)
    dot = hidden_dot.clone()
    dot.move(center.getX() + 5, center.getY() + 5)
    dot.draw(win)
    dot = hidden_dot.clone()
    dot.move(center.getX() + 5, center.getY() - 5)
    dot.draw(win)

    five = four.clone()
    five.move(210 * 2/7, 0)
    five.draw(win)
    center = five.getCenter()
    dot = hidden_dot.clone()
    dot.move(center.getX(), center.getY())
    dot.draw(win)
    dot = hidden_dot.clone()
    dot.move(center.getX() - 7, center.getY() + 7)
    dot.draw(win)
    dot = hidden_dot.clone()
    dot.move(center.getX() - 7, center.getY() - 7)
    dot.draw(win)
    dot = hidden_dot.clone()
    dot.move(center.getX() + 7, center.getY() + 7)
    dot.draw(win)
    dot = hidden_dot.clone()
    dot.move(center.getX() + 7, center.getY() - 7)
    dot.draw(win)
 
    win.getMouse()
    win.close()
    
main()